import unittest
from Task_14_1 import BastShoe

class func_test(unittest.TestCase):
    def test_right_output(self):
        self.assertEqual(BastShoe("1 Привет"), "Привет")
        self.assertEqual(BastShoe("1 , Мир!"), "Привет, Мир!")
        self.assertEqual(BastShoe("1 **"), "Привет, Мир!**")
        self.assertEqual(BastShoe("2 2"), "Привет, Мир!")
        self.assertEqual(BastShoe("4"), "Привет, Мир!**")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("4"), "Привет, Мир!**")
        self.assertEqual(BastShoe("4"), "Привет, Мир!")
        self.assertEqual(BastShoe("4"), "Привет")
        self.assertEqual(BastShoe("4"), "")
        self.assertEqual(BastShoe("4"), "")
        self.assertEqual(BastShoe("4"), "")
        self.assertEqual(BastShoe("5"), "Привет")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("5"), "Привет, Мир!**")
        self.assertEqual(BastShoe("2 2"), "Привет, Мир!")
        self.assertEqual(BastShoe("4"), "Привет, Мир!**")
        self.assertEqual(BastShoe("4"), "Привет, Мир!**")
        self.assertEqual(BastShoe("4"), "Привет, Мир!**")
        self.assertEqual(BastShoe("4"), "Привет, Мир!**")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("6"), "Привет, Мир!")
        self.assertEqual(BastShoe("a"), "Привет, Мир!")
        self.assertEqual(BastShoe("2 200"), "")
        self.assertEqual(BastShoe("1 Hello"), "Hello")
        self.assertEqual(BastShoe("1 , World!"), "Hello, World!")
        self.assertEqual(BastShoe("1 ++"), "Hello, World!++")
        self.assertEqual(BastShoe("1 **"), "Hello, World!++**")
        self.assertEqual(BastShoe("4"), "Hello, World!++")
        self.assertEqual(BastShoe("1 **"), "Hello, World!++**")
        self.assertEqual(BastShoe("4"), "Hello, World!++")
        self.assertEqual(BastShoe("4"), "Hello, World!++")
        self.assertEqual(BastShoe("4"), "Hello, World!++")
        self.assertEqual(BastShoe("4"), "Hello, World!++")
        self.assertEqual(BastShoe("4"), "Hello, World!++")
        self.assertEqual(BastShoe("4"), "Hello, World!++")
        self.assertEqual(BastShoe("4"), "Hello, World!++")
        self.assertEqual(BastShoe("5"), "Hello, World!++**")
        self.assertEqual(BastShoe("5"), "Hello, World!++**")
        self.assertEqual(BastShoe("5"), "Hello, World!++**")
        self.assertEqual(BastShoe("5"), "Hello, World!++**")
        self.assertEqual(BastShoe("5"), "Hello, World!++**")
        self.assertEqual(BastShoe("5"), "Hello, World!++**")
        self.assertEqual(BastShoe("2 200"), "")
        self.assertEqual(BastShoe("1 Привет"), "Привет")
        self.assertEqual(BastShoe("1 ++"), "Привет++")
        self.assertEqual(BastShoe("4"), "Привет")
        self.assertEqual(BastShoe("1 , Мир!"), "Привет, Мир!")
        self.assertEqual(BastShoe("4"), "Привет")
        self.assertEqual(BastShoe("4"), "Привет")
        self.assertEqual(BastShoe("4"), "Привет")
        self.assertEqual(BastShoe("4"), "Привет")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("2 200"), "")
        self.assertEqual(BastShoe("1 Привет"), "Привет")
        self.assertEqual(BastShoe("4"), "")
        self.assertEqual(BastShoe("1 Мир!"), "Мир!")
        self.assertEqual(BastShoe("4"), "")
        self.assertEqual(BastShoe("4"), "")
        self.assertEqual(BastShoe("4"), "")
        self.assertEqual(BastShoe("4"), "")
        self.assertEqual(BastShoe("5"), "Мир!")
        self.assertEqual(BastShoe("5"), "Мир!")
        self.assertEqual(BastShoe("5"), "Мир!")
        self.assertEqual(BastShoe("5"), "Мир!")
        self.assertEqual(BastShoe("5"), "Мир!")

        

if __name__ == '__main__':
    unittest.main()